PROJECTS := \
	array\
	array_view\
	expression\
	functional\
	interpolation\
	math\
	matrix\
	meta\
	numerical_derivate\
	quaternion\
	rational\
	ref

# Default compilation flags.
CXXFLAGS := -std=c++98 -I ../include/ -I ~/usr/include/

# Includes MyGreatMakefile
include ../tools/mgm/mgm.mk
